import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Script from "next/script";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Dulani Lamahewage",
  description: "Generated by DRL",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load the external EmailJS script */}
        <Script
                src="https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js"
                strategy="beforeInteractive" // Loads before the page becomes interactive
              />

              {/* Inline script to initialize EmailJS */}
              <Script id="emailjs-init" strategy="afterInteractive">
                {`
                  (function() {
                    emailjs.init("8F0LP6JJTBPkonSD5");
                    console.log('EmailJS initialized');
                  })();
                `}
              </Script>
      </head>
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
